package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petfotoguia generated by hbm2java
 */
@Entity
@Table(name = "petfotoguia", schema = "pets")
public class Petfotoguia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2201429434978763295L;
	private int idfotoguia;
	private Setestado setestado;
	private Setusuario setusuario;
	private Petguia petguia;
	private String descripcion;
	private String ruta;
	private String nombrearchivo;
	private Integer perfil;
	private Date fecharegistro;
	private String iplog;

	public Petfotoguia() {
	}

	public Petfotoguia(int idfotoguia, Petguia petguia, Date fecharegistro) {
		this.idfotoguia = idfotoguia;
		this.petguia = petguia;
		this.fecharegistro = fecharegistro;
	}

	public Petfotoguia(int idfotoguia, Setestado setestado,
			Setusuario setusuario, Petguia petguia, String descripcion,
			String ruta, String nombrearchivo, Integer perfil,
			Date fecharegistro, String iplog) {
		this.idfotoguia = idfotoguia;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.petguia = petguia;
		this.descripcion = descripcion;
		this.ruta = ruta;
		this.nombrearchivo = nombrearchivo;
		this.perfil = perfil;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idfotoguia", unique = true, nullable = false)
	public int getIdfotoguia() {
		return this.idfotoguia;
	}

	public void setIdfotoguia(int idfotoguia) {
		this.idfotoguia = idfotoguia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idguia", nullable = false)
	public Petguia getPetguia() {
		return this.petguia;
	}

	public void setPetguia(Petguia petguia) {
		this.petguia = petguia;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "nombrearchivo", length = 50)
	public String getNombrearchivo() {
		return this.nombrearchivo;
	}

	public void setNombrearchivo(String nombrearchivo) {
		this.nombrearchivo = nombrearchivo;
	}

	@Column(name = "perfil")
	public Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Integer perfil) {
		this.perfil = perfil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
