package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petfotonoticia generated by hbm2java
 */
@Entity
@Table(name = "petfotonoticia", schema = "pets")
public class Petfotonoticia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8518528071052329289L;
	private int idfotonoticia;
	private Setestado setestado;
	private Petnoticia petnoticia;
	private Setusuario setusuario;
	private String descripcion;
	private String ruta;
	private String nombrearchivo;
	private Integer perfil;
	private Date fecharegistro;
	private String iplog;

	public Petfotonoticia() {
	}

	public Petfotonoticia(int idfotonoticia, Petnoticia petnoticia,
			Date fecharegistro) {
		this.idfotonoticia = idfotonoticia;
		this.petnoticia = petnoticia;
		this.fecharegistro = fecharegistro;
	}

	public Petfotonoticia(int idfotonoticia, Setestado setestado,
			Petnoticia petnoticia, Setusuario setusuario, String descripcion,
			String ruta, String nombrearchivo, Integer perfil,
			Date fecharegistro, String iplog) {
		this.idfotonoticia = idfotonoticia;
		this.setestado = setestado;
		this.petnoticia = petnoticia;
		this.setusuario = setusuario;
		this.descripcion = descripcion;
		this.ruta = ruta;
		this.nombrearchivo = nombrearchivo;
		this.perfil = perfil;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idfotonoticia", unique = true, nullable = false)
	public int getIdfotonoticia() {
		return this.idfotonoticia;
	}

	public void setIdfotonoticia(int idfotonoticia) {
		this.idfotonoticia = idfotonoticia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnoticia", nullable = false)
	public Petnoticia getPetnoticia() {
		return this.petnoticia;
	}

	public void setPetnoticia(Petnoticia petnoticia) {
		this.petnoticia = petnoticia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "nombrearchivo", length = 50)
	public String getNombrearchivo() {
		return this.nombrearchivo;
	}

	public void setNombrearchivo(String nombrearchivo) {
		this.nombrearchivo = nombrearchivo;
	}

	@Column(name = "perfil")
	public Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Integer perfil) {
		this.perfil = perfil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
