package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petfotoservicio generated by hbm2java
 */
@Entity
@Table(name = "petfotoservicio", schema = "pets")
public class Petfotoservicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6125303342372378500L;
	private int idfotoservicio;
	private Setestado setestado;
	private Setusuario setusuario;
	private Petservicio petservicio;
	private String descripcion;
	private String ruta;
	private String nombrearchivo;
	private Integer perfil;
	private Date fecharegistro;
	private String iplog;

	public Petfotoservicio() {
	}

	public Petfotoservicio(int idfotoservicio, Petservicio petservicio,
			Date fecharegistro) {
		this.idfotoservicio = idfotoservicio;
		this.petservicio = petservicio;
		this.fecharegistro = fecharegistro;
	}

	public Petfotoservicio(int idfotoservicio, Setestado setestado,
			Setusuario setusuario, Petservicio petservicio, String descripcion,
			String ruta, String nombrearchivo, Integer perfil,
			Date fecharegistro, String iplog) {
		this.idfotoservicio = idfotoservicio;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.petservicio = petservicio;
		this.descripcion = descripcion;
		this.ruta = ruta;
		this.nombrearchivo = nombrearchivo;
		this.perfil = perfil;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idfotoservicio", unique = true, nullable = false)
	public int getIdfotoservicio() {
		return this.idfotoservicio;
	}

	public void setIdfotoservicio(int idfotoservicio) {
		this.idfotoservicio = idfotoservicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idservicio", nullable = false)
	public Petservicio getPetservicio() {
		return this.petservicio;
	}

	public void setPetservicio(Petservicio petservicio) {
		this.petservicio = petservicio;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "nombrearchivo", length = 50)
	public String getNombrearchivo() {
		return this.nombrearchivo;
	}

	public void setNombrearchivo(String nombrearchivo) {
		this.nombrearchivo = nombrearchivo;
	}

	@Column(name = "perfil")
	public Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Integer perfil) {
		this.perfil = perfil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
