package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petguia generated by hbm2java
 */
@Entity
@Table(name = "petguia", schema = "pets")
public class Petguia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9018132792136466347L;
	private int idguia;
	private Setestado setestado;
	private Setusuario setusuario;
	private String titulo;
	private String descripcion;
	private String tag;
	private Date fecharegistro;
	private String iplog;
	private Set<?> petfotoguias = new HashSet<Object>(0);

	public Petguia() {
	}

	public Petguia(int idguia, Date fecharegistro) {
		this.idguia = idguia;
		this.fecharegistro = fecharegistro;
	}

	public Petguia(int idguia, Setestado setestado, Setusuario setusuario,
			String titulo, String descripcion, String tag, Date fecharegistro,
			String iplog, Set<?> petfotoguias) {
		this.idguia = idguia;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.tag = tag;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petfotoguias = petfotoguias;
	}

	@Id
	@Column(name = "idguia", unique = true, nullable = false)
	public int getIdguia() {
		return this.idguia;
	}

	public void setIdguia(int idguia) {
		this.idguia = idguia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "titulo", length = 1000)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 5000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tag", length = 200)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petguia", targetEntity=Petfotoguia.class)
	public Set<?> getPetfotoguias() {
		return this.petfotoguias;
	}

	public void setPetfotoguias(Set<?> petfotoguias) {
		this.petfotoguias = petfotoguias;
	}

}
