package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petinformacion generated by hbm2java
 */
@Entity
@Table(name = "petinformacion", schema = "pets")
public class Petinformacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 432554490645345420L;
	private int idinformacion;
	private Setestado setestado;
	private Setusuario setusuario;
	private String quienessomos;
	private String mision;
	private String vision;
	private String antecendentes;
	private String fotoquienessomos;
	private String fotoantecedentes;
	private Date fecharegistro;
	private String iplog;
	private String tag;
	private Set<?> petfotoinformacions = new HashSet<Object>(0);

	public Petinformacion() {
	}

	public Petinformacion(int idinformacion, String quienessomos,
			Date fecharegistro) {
		this.idinformacion = idinformacion;
		this.quienessomos = quienessomos;
		this.fecharegistro = fecharegistro;
	}

	public Petinformacion(int idinformacion, Setestado setestado,
			Setusuario setusuario, String quienessomos, String mision,
			String vision, String antecendentes, String fotoantecedentes,
			String fotoquienessomos,Date fecharegistro,
			String iplog, String tag, Set<?> petfotoinformacions) {
		this.idinformacion = idinformacion;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.quienessomos = quienessomos;
		this.mision = mision;
		this.vision = vision;
		this.antecendentes = antecendentes;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.tag = tag;
		this.petfotoinformacions = petfotoinformacions;
		this.fotoantecedentes = fotoantecedentes;
		this.fotoquienessomos = fotoquienessomos;
	}

	@Id
	@Column(name = "idinformacion", unique = true, nullable = false)
	public int getIdinformacion() {
		return this.idinformacion;
	}

	public void setIdinformacion(int idinformacion) {
		this.idinformacion = idinformacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "quienessomos", nullable = false, length = 2000)
	public String getQuienessomos() {
		return this.quienessomos;
	}

	public void setQuienessomos(String quienessomos) {
		this.quienessomos = quienessomos;
	}
	
	@Column(name = "fotoquienessomos",nullable = false, length = 100)
	public String getFotoquienessomos(){
		return this.fotoquienessomos;
	}
	
    public void setFotoquienessomos(String fotoquienessomos){
    	this.fotoquienessomos = fotoquienessomos;
    }
	
	@Column(name = "mision", length = 2000)
	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	@Column(name = "vision", length = 2000)
	public String getVision() {
		return this.vision;
	}

	public void setVision(String vision) {
		this.vision = vision;
	}

	@Column(name = "antecendentes", length = 5000)
	public String getAntecendentes() {
		return this.antecendentes;
	}

	public void setAntecendentes(String antecendentes) {
		this.antecendentes = antecendentes;
	}

	@Column (name = "fotoantecedentes",length = 100)
	public String getFotoantecedentes(){
		return this.fotoantecedentes;
	}
	
	public void setFotoantecedentes(String fotoantecedentes){
		this.fotoantecedentes = fotoantecedentes;
	}
	
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "tag", length = 200)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petinformacion", targetEntity=Petfotoinformacion.class)
	public Set<?> getPetfotoinformacions() {
		return this.petfotoinformacions;
	}

	public void setPetfotoinformacions(Set<?> petfotoinformacions) {
		this.petfotoinformacions = petfotoinformacions;
	}

}
