package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petmascotahomenaje generated by hbm2java
 */
@Entity
@Table(name = "petmascotahomenaje", schema = "pets")
public class Petmascotahomenaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6299529275804346070L;
	private int idmascota;
	private Setestado setestado;
	private Setusuario setusuario;
	private Petespecie petespecie;
	private String nombre;
	private Date fechanacimiento;
	private Date fechafallecimiento;
	private Date fechapublicacion;
	private String familia;
	private String dedicatoria;
	private String tag;
	private String rutafoto;
	private Date fecharegistro;
	private Date fechamodificacion;
	private String iplog;
	private Set<?> petfotomascotas = new HashSet<Object>(0);

	public Petmascotahomenaje() {
	}

	public Petmascotahomenaje(int idmascota, Date fecharegistro) {
		this.idmascota = idmascota;
		this.fecharegistro = fecharegistro;
	}

	public Petmascotahomenaje(int idmascota, Setestado setestado,
			Setusuario setusuario, Petespecie petespecie, String nombre,
			Date fechanacimiento, Date fechafallecimiento, Date fechapublicacion,
			String familia,String dedicatoria, String tag, String rutafoto,Date fecharegistro,
			Date fechamodificacion,String iplog,
			Set<?> petfotomascotas) {
		this.idmascota = idmascota;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.petespecie = petespecie;
		this.nombre = nombre;
		this.fechanacimiento = fechanacimiento;
		this.fechafallecimiento = fechafallecimiento;
		this.fechapublicacion = fechapublicacion;
		this.familia = familia;
		this.dedicatoria = dedicatoria;
		this.tag = tag;
		this.rutafoto = rutafoto;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.iplog = iplog;
		this.petfotomascotas = petfotomascotas;
	}

	@Id
	@Column(name = "idmascota", unique = true, nullable = false)
	public int getIdmascota() {
		return this.idmascota;
	}

	public void setIdmascota(int idmascota) {
		this.idmascota = idmascota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idespecie")
	public Petespecie getPetespecie() {
		return this.petespecie;
	}

	public void setPetespecie(Petespecie petespecie) {
		this.petespecie = petespecie;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechanacimiento", length = 29)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafallecimiento", length = 29)
	public Date getFechafallecimiento() {
		return this.fechafallecimiento;
	}

	public void setFechafallecimiento(Date fechafallecimiento) {
		this.fechafallecimiento = fechafallecimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechapublicacion", length = 29)
	public Date getFechapublicacion() {
		return this.fechapublicacion;
	}

	public void setFechapublicacion(Date fechapublicacion) {
		this.fechapublicacion = fechapublicacion;
	}

	@Column(name = "familia", length = 200)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	@Column(name = "dedicatoria", length = 2000)
	public String getDedicatoria() {
		return this.dedicatoria;
	}

	public void setDedicatoria(String dedicatoria) {
		this.dedicatoria = dedicatoria;
	}

	@Column(name = "tag", length = 200)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
	
	@Column(name = "rutafoto", length = 100)
	public String getRutafoto() {
		return this.rutafoto;
	}

	public void setRutafoto(String rutafoto) {
		this.rutafoto = rutafoto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamodificacion",  length = 29)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}
	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascotahomenaje", targetEntity=Petfotomascota.class)
	public Set<?> getPetfotomascotas() {
		return this.petfotomascotas;
	}

	public void setPetfotomascotas(Set<?> petfotomascotas) {
		this.petfotomascotas = petfotomascotas;
	}

}
